import React from 'react';
import { Scale, ShieldCheck, Wrench, Ban, AlertTriangle, Globe, Siren } from 'lucide-react';

export default function LicenseModal({ onClose }) {
  return (
    <div className="fixed inset-0 bg-zinc-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-2xl max-h-[85vh] rounded-2xl shadow-2xl border border-gray-100 flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="px-8 py-6 border-b border-gray-100 flex justify-between items-start bg-white shrink-0">
          <div>
            <h2 className="text-2xl font-bold text-zinc-900 flex items-center gap-3 tracking-tight">
              <Scale className="w-7 h-7 text-indigo-600" />
              Software License
            </h2>
            <div className="mt-2 flex flex-col gap-1">
              <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wider">License Type: Proprietary Institutional License</p>
              <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wider">Effective Date: 17 February 2026</p>
            </div>
          </div>
        </div>

        {/* Scrollable Content */}
        <div className="p-8 overflow-y-auto space-y-8 text-sm text-gray-600 leading-relaxed custom-scrollbar">
          
          {/* Official Grant Preamble */}
          <div className="bg-blue-50/50 p-5 rounded-2xl border border-blue-100">
            <p className="text-sm text-zinc-900">
              <strong className="text-blue-700 block mb-1">GRANT:</strong> 
              This Software is expressly provided <strong className="text-zinc-900">free-of-charge</strong> to the <strong className="text-zinc-900">Abra Provincial Health Office</strong> for use by its authorized health facilities, including government-operated and accredited private Animal Bite Treatment Centers. It serves as a dedicated modernization initiative.
            </p>
          </div>

          {/* Section 1 */}
          <section>
            <h3 className="text-base text-zinc-900 font-bold mb-3 flex items-center gap-2">
              <ShieldCheck size={20} className="text-blue-500" />
              Section 1 - Ownership and Copyright Infringement
            </h3>
            <p className="mb-2">
              The <strong className="text-zinc-900">ABTC Reporting System</strong> ("Software"), including all source code, database schemas, and design elements, constitutes the proprietary intellectual property of <strong className="text-zinc-900">Justice Belleza</strong>.
            </p>
            <p className="text-xs font-semibold text-gray-400 mb-5">© 2026 Justice Belleza. All Rights Reserved.</p>

            <strong className="block text-zinc-900 text-xs uppercase tracking-wider mb-2">Section 1.1 Data Ownership</strong>
            <p>
              While the Software source code remains the property of the Developer, all statistical data, reports, and database records generated by the System shall be the exclusive property of the <strong className="text-zinc-900">Abra Provincial Health Office</strong>.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h3 className="text-base text-zinc-900 font-bold mb-3 flex items-center gap-2">
              <Wrench size={20} className="text-emerald-500" />
              Section 2 - Maintenance and Succession Rights
            </h3>
            <p className="mb-5">
              To ensure the sustainability of public health reporting, <strong className="text-zinc-900">in the event that the Developer's contract is terminated or not renewed</strong>, the following succession plan shall govern:
            </p>
            
            <div className="space-y-6 pl-1">
              <div className="bg-gray-50 p-5 rounded-2xl border border-gray-100">
                <strong className="text-zinc-900 text-xs uppercase tracking-wider block mb-3">A. Transfer of Assets and Costs</strong>
                <p className="mb-3">Operational costs (hosting, domain, and database subscriptions) currently borne by the Developer shall transfer to the Abra Provincial Health Office. The Developer shall:</p>
                <ol className="list-decimal pl-5 space-y-2">
                  <li><strong className="text-zinc-900">Domain:</strong> Transfer ownership of the internet domain name to the Office.</li>
                  <li><strong className="text-zinc-900">Database:</strong> Grant full administrative access and billing ownership of the <strong className="text-zinc-900">managed database infrastructure</strong> to the Office.</li>
                  <li><strong className="text-zinc-900">Hosting:</strong> Facilitate the creation of a new Hostinger account (or equivalent) for the Office and migrate the hosting environment.</li>
                </ol>
              </div>

              <div className="bg-gray-50 p-5 rounded-2xl border border-gray-100">
                <strong className="text-zinc-900 text-xs uppercase tracking-wider block mb-3">B. Transition Period (Grace Period)</strong>
                <p>
                  The Developer shall maintain the active status of these accounts for <strong className="text-zinc-900">thirty (30) days</strong> following contract termination to allow the Office sufficient time to assume billing responsibility. Failure of the Office to assume financial responsibility within said period releases the Developer from any obligation to maintain service availability.
                </p>
              </div>

              <div className="bg-gray-50 p-5 rounded-2xl border border-gray-100">
                <strong className="text-zinc-900 text-xs uppercase tracking-wider block mb-3">C. Source Code Access</strong>
                <p className="mb-3">
                  The <strong className="text-zinc-900">Designated IT Officer</strong> of the Abra Provincial Health Office is granted a limited, perpetual right to access and modify the Software source code <strong className="text-zinc-900">solely</strong> for:
                </p>
                <ul className="list-disc pl-5 space-y-1 mb-4">
                  <li>Internal maintenance and bug fixing</li>
                  <li>Platform compatibility updates</li>
                  <li>Security patching</li>
                </ul>
                <p className="text-[11px] font-bold uppercase tracking-wider text-rose-500">
                  Note: Individual health facilities are not authorized to modify the source code.
                </p>
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h3 className="text-base text-zinc-900 font-bold mb-3 flex items-center gap-2">
              <Ban size={20} className="text-rose-500" />
              Section 3 - Restrictions
            </h3>
            <p className="mb-3">Unless expressly authorized in writing by the Developer, no person or entity may:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Sell, sublicense, lease, or rent the Software to any third party.</li>
              <li>Distribute the Software outside the Province of Abra health network.</li>
              <li>Reverse engineer, decompile, or disassemble the Software.</li>
              <li>Claim authorship of the Software.</li>
              <li>Use the Software for commercial gain outside of official reporting duties.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h3 className="text-base text-zinc-900 font-bold mb-3 flex items-center gap-2">
              <AlertTriangle size={20} className="text-amber-500" />
              Section 4 - Disclaimer of Warranty ("AS IS")
            </h3>
            <div className="bg-amber-50/50 p-5 rounded-2xl border border-amber-100">
                <p className="uppercase text-[11px] font-bold tracking-wider text-amber-600 mb-2">Provided "AS IS"</p>
                <p className="text-sm font-medium text-amber-900/80 leading-relaxed">
                  The Software code is provided "AS IS," without warranty of any kind, express or implied. While the Developer endeavors to maintain service availability during the contract period, the Developer shall not be liable for damages, data loss, or reporting inaccuracies arising from the use or malfunction of the Software.
                </p>
            </div>
          </section>

          {/* Section 5 & 6 (Stacked) */}
          <div className="space-y-8 pt-6 border-t border-gray-100">
            <section>
              <h3 className="text-base text-zinc-900 font-bold mb-2 flex items-center gap-2">
                <Globe size={18} className="text-cyan-600" />
                Section 5 - Jurisdiction
              </h3>
              <p>
                This License shall be governed by the laws of the Republic of the Philippines. Disputes regarding intellectual property or usage rights shall be resolved exclusively before the courts of the <strong className="text-zinc-900">Province of Abra</strong>.
              </p>
            </section>
            <section>
              <h3 className="text-base text-rose-600 font-bold mb-2 flex items-center gap-2">
                <Siren size={18} className="text-rose-500" />
                Section 6 - Termination of Grant
              </h3>
              <p>
                The Developer reserves the right to terminate this License Grant immediately if the Abra Provincial Health Office violates the restrictions set forth in Section 3, particularly regarding unauthorized distribution or commercial use of the Software.
              </p>
            </section>
          </div>

        </div>

        {/* Footer */}
        <div className="px-8 py-5 border-t border-gray-100 bg-gray-50/80 shrink-0 flex justify-center">
          <button 
            onClick={onClose}
            className="px-10 py-3 bg-zinc-900 text-white text-sm font-semibold rounded-xl hover:bg-zinc-800 hover:shadow-lg hover:shadow-zinc-900/20 active:scale-[0.98] transition-all"
          >
            Understood
          </button>
        </div>

      </div>
    </div>
  );
}