import React from 'react';
import { Scale, ShieldCheck, Wrench, Ban, AlertTriangle, Globe, Siren } from 'lucide-react';

export default function LicenseModal({ onClose }) {
  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-2xl max-h-[85vh] rounded-xl shadow-2xl flex flex-col overflow-hidden">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-zinc-100 flex justify-between items-center bg-white shrink-0">
          <div>
            <h2 className="text-lg font-bold text-zinc-900 flex items-center gap-2">
              <Scale className="w-6 h-6 text-indigo-600" />
              Software License
            </h2>
            <p className="text-xs text-zinc-500 mt-1">License Type: Proprietary (Institutional Grant)</p>
          </div>
        </div>

        {/* Scrollable Content */}
        <div className="p-6 overflow-y-auto space-y-8 text-sm text-zinc-600 leading-relaxed">
          
          {/* Official Grant Preamble */}
          <div className="bg-zinc-50 p-4 rounded-lg border border-zinc-100">
            <p>
              <strong>OFFICIAL GRANT:</strong> This software is expressly provided <strong>FREE OF CHARGE</strong> to the <strong>Abra Provincial Health Office</strong> for use by its authorized Health Facilities (including government-operated and accredited private Animal Bite Treatment Centers). It is a dedicated modernization initiative.
            </p>
          </div>

          {/* Section 1 */}
          <section>
            <h3 className="text-zinc-900 font-semibold mb-2 flex items-center gap-2">
              <ShieldCheck size={18} className="text-blue-600" />
              1. Ownership & Copyright
            </h3>
            <p className="mb-2">
              The <strong>ABTC Reporting System</strong> (the "Software"), including all source code, database schemas, and design elements, is the proprietary intellectual property of <strong>Justice Belleza</strong>.
            </p>
            <p className="text-xs text-zinc-500 mb-4">© 2026 Justice Belleza. All Rights Reserved.</p>

            <strong className="block text-zinc-900 text-xs mb-1">1.1 Data Ownership</strong>
            <p>
              While the Software source code remains the property of the Developer, all statistical data, reports, and database records generated by the System are the sole property of the <strong>Abra Provincial Health Office</strong>.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h3 className="text-zinc-900 font-semibold mb-2 flex items-center gap-2">
              <Wrench size={18} className="text-emerald-600" />
              2. Maintenance & Succession Rights
            </h3>
            <p className="mb-3">
              To ensure the sustainability of public health reporting, <strong>specifically in the event that the Developer's contract is ended or not renewed</strong>, the following succession plan shall take effect:
            </p>
            
            <div className="space-y-4 pl-1">
              <div>
                <strong className="text-zinc-800 text-xs uppercase block mb-1">A. Transfer of Assets & Costs</strong>
                <p className="mb-1">The operational costs (Hosting, Domain, and Database subscriptions) currently shouldered by the Developer shall transfer to the Abra Provincial Health Office. The Developer agrees to:</p>
                <ol className="list-decimal pl-5 space-y-1">
                  <li><strong>Domain:</strong> Transfer ownership of the internet domain name to the Office.</li>
                  <li><strong>Database:</strong> Grant full administrative access and billing ownership of the <strong>Managed Database Infrastructure</strong> to the Office.</li>
                  <li><strong>Hosting:</strong> Facilitate the creation of a new Hostinger account (or equivalent) for the Office and migrate the hosting environment.</li>
                </ol>
              </div>

              <div>
                <strong className="text-zinc-800 text-xs uppercase block mb-1">B. Transition Period (Grace Period)</strong>
                <p>
                  The Developer agrees to maintain the active status of these accounts for a grace period of <strong>thirty (30) days</strong> following contract termination. Failure of the Office to assume financial responsibility after 30 days releases the Developer from any obligation to maintain service availability.
                </p>
              </div>

              <div>
                <strong className="text-zinc-800 text-xs uppercase block mb-1">C. Source Code Access</strong>
                <p className="mb-1">
                  The <strong>Designated IT Officer</strong> of the Abra Provincial Health Office is granted a limited, perpetual right to access and modify the Software source code <strong>SOLELY</strong> for:
                </p>
                <ul className="list-disc pl-5 space-y-1 mb-2">
                  <li>Internal maintenance and bug fixing.</li>
                  <li>Platform compatibility updates.</li>
                  <li>Security patching.</li>
                </ul>
                <p className="text-xs italic text-zinc-500">
                  <strong>NOTE:</strong> Individual Health Facilities are <strong>NOT</strong> authorized to modify the source code.
                </p>
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h3 className="text-zinc-900 font-semibold mb-2 flex items-center gap-2">
              <Ban size={18} className="text-rose-600" />
              3. Restrictions
            </h3>
            <p className="mb-2">Unless expressly authorized in writing by the Developer, no person or entity may:</p>
            <ul className="list-disc pl-4 space-y-1">
              <li>Sell, sublicense, lease, or rent the Software to any third party.</li>
              <li>Distribute the Software outside the Province of Abra health network.</li>
              <li>Reverse engineer, decompile, or disassemble the Software.</li>
              <li>Claim authorship of the Software.</li>
              <li>Use the Software for commercial gain outside of official reporting duties.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h3 className="text-zinc-900 font-semibold mb-2 flex items-center gap-2">
              <AlertTriangle size={18} className="text-amber-600" />
              4. Disclaimer of Warranty (Code "AS IS")
            </h3>
            <p className="uppercase text-xs font-bold text-zinc-400 mb-1">Provided "AS IS"</p>
            <p className="italic">
              THE SOFTWARE CODE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WHILE THE DEVELOPER ENDEAVORS TO MAINTAIN SERVICE AVAILABILITY DURING THE CONTRACT PERIOD, THE DEVELOPER SHALL NOT BE LIABLE FOR DAMAGES, DATA LOSS, OR REPORTING INACCURACIES ARISING FROM THE USE OR MALFUNCTION OF THIS SOFTWARE.
            </p>
          </section>

          {/* Section 5 & 6 (Stacked) */}
          <div className="space-y-6 pt-4 border-t border-zinc-100">
            <section>
              <h3 className="text-zinc-900 font-semibold mb-1 flex items-center gap-2">
                <Globe size={16} className="text-cyan-600" />
                5. Jurisdiction
              </h3>
              <p>
                This License is governed by the laws of the Republic of the Philippines. Disputes regarding intellectual property or usage rights shall be resolved exclusively in the courts of the <strong>Province of Abra</strong>.
              </p>
            </section>
            <section>
              <h3 className="text-red-700 font-semibold mb-1 flex items-center gap-2">
                <Siren size={16} className="text-red-600" />
                6. Termination of Grant
              </h3>
              <p>
                The Developer reserves the right to terminate this License Grant immediately if the Abra Provincial Health Office violates the Restrictions outlined in Section 3, particularly regarding unauthorized distribution or commercial use of the Software.
              </p>
            </section>
          </div>

        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-zinc-100 bg-zinc-50 shrink-0 flex justify-center">
          <button 
            onClick={onClose}
            className="px-8 py-2.5 bg-zinc-900 hover:bg-zinc-800 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
          >
            Understood
          </button>
        </div>

      </div>
    </div>
  );
}